[
  {
    tags: ["React", "Frontend", "JavaScript"],
    _id: "service-1",
    secondCategory: "Разработка",
    alias: "react-website-development",
    title: "Разработка веб-сайта на React",
    seoText:
      "Создание современных веб-сайтов на React с высокой производительностью.",
    tagsTitle: "Сервисы React-разработки",
    metaTitle: "Разработка веб-сайта на React - Профессиональные услуги",
    metaDescription:
      "Разработка веб-сайтов на React с использованием современных технологий.",
    firstCategory: 0,
    advantages: [
      {
        _id: "adv-1",
        title: "Адаптивный дизайн",
        description: "Создание адаптивного дизайна для различных устройств.",
      },
      {
        _id: "adv-2",
        title: "Высокая производительность",
        description: "Оптимизация для быстрой загрузки и работы.",
      },
    ],
    createAt: "2023-01-01T00:00:00.000Z",
    updateAt: "2023-03-01T00:00:00.000Z",
    hh: {
      _id: "hh-1",
      count: 150,
      juniorSalary: 60000,
      middleSalary: 90000,
      seniorSalary: 120000,
      updateAt: "2023-02-15T00:00:00.000Z",
    },
  },
  {
    tags: ["Mobile", "iOS", "Android"],
    _id: "service-2",
    secondCategory: "Разработка",
    alias: "mobile-app-development",
    title: "Разработка мобильного приложения",
    seoText:
      "Создание мобильных приложений для iOS и Android с учетом последних трендов.",
    tagsTitle: "Сервисы мобильной разработки",
    metaTitle: "Разработка мобильного приложения - Закажите сейчас!",
    metaDescription:
      "Профессиональная разработка мобильных приложений для вашего бизнеса.",
    firstCategory: 0,
    advantages: [
      {
        _id: "adv-3",
        title: "Кроссплатформенность",
        description: "Разработка приложений для обеих платформ.",
      },
      {
        _id: "adv-4",
        title: "Интуитивный UI/UX",
        description: "Создание удобного пользовательского интерфейса.",
      },
    ],
    createAt: "2023-02-01T00:00:00.000Z",
    updateAt: "2023-03-01T00:00:00.000Z",
    hh: {
      _id: "hh-2",
      count: 100,
      juniorSalary: 70000,
      middleSalary: 95000,
      seniorSalary: 130000,
      updateAt: "2023-02-20T00:00:00.000Z",
    },
  },
  {
    tags: ["Chatbot", "AI", "Automation"],
    _id: "service-3",
    secondCategory: "Разработка",
    alias: "chatbot-development",
    title: "Разработка чат-бота",
    seoText:
      "Разработка чат-ботов для автоматизации общения с клиентами и улучшения поддержки.",
    tagsTitle: "Сервисы разработки чат-ботов",
    metaTitle: "Разработка чат-бота - Улучшите взаимодействие с клиентами",
    metaDescription:
      "Разработка интеллектуальных чат-ботов для вашего бизнеса.",
    firstCategory: 0,
    advantages: [
      {
        _id: "adv-5",
        title: "Круглосуточная поддержка",
        description: "Обеспечение круглосуточной поддержки клиентов.",
      },
      {
        _id: "adv-6",
        title: "Интеграция с CRM",
        description:
          "Интеграция с системами управления взаимоотношениями с клиентами.",
      },
    ],
    createAt: "2023-02-01T00:00:00.000Z",
    updateAt: "2023-03-01T00:00:00.000Z",
    hh: {
      _id: "hh-2",
      count: 100,
      juniorSalary: 70000,
      middleSalary: 95000,
      seniorSalary: 130000,
      updateAt: "2023-02-20T00:00:00.000Z",
    },
  },
  {
    tags: ["Instagram", "Social Media", "Marketing"],
    _id: "service-4",
    secondCategory: "Маркетинг",
    alias: "instagram-promotion",
    title: "Продвижение в Instagram",
    seoText:
      "Продвижение вашего бренда в Instagram с помощью эффективных стратегий.",
    tagsTitle: "Сервисы продвижения в Instagram",
    metaTitle: "Продвижение в Instagram - Увеличьте свою аудиторию",
    metaDescription:
      "Увеличение узнаваемости бренда и привлечение новых клиентов через Instagram.",
    firstCategory: 1,
    advantages: [
      {
        _id: "adv-7",
        title: "Таргетированная реклама",
        description:
          "Настройка таргетированной рекламы для привлечения целевой аудитории.",
      },
      {
        _id: "adv-8",
        title: "Контент-стратегия",
        description:
          "Разработка контент-стратегии для повышения вовлеченности.",
      },
    ],
    createAt: "2023-03-01T00:00:00.000Z",
    updateAt: "2023-03-05T00:00:00.000Z",
    hh: {
      _id: "hh-3",
      count: 80,
      juniorSalary: 50000,
      middleSalary: 75000,
      seniorSalary: 100000,
      updateAt: "2023-02-25T00:00:00.000Z",
    },
  },
  {
    tags: ["Email", "Marketing Automation", "CRM"],
    _id: "service-5",
    secondCategory: "Маркетинг",
    alias: "email-marketing",
    title: "Email-маркетинг",
    seoText:
      "Эффективные email-кампании для повышения лояльности клиентов и увеличения продаж.",
    tagsTitle: "Сервисы email-маркетинга",
    metaTitle: "Email-маркетинг - Увеличьте свои продажи",
    metaDescription:
      "Создание и управление email-кампаниями для вашего бизнеса.",
    firstCategory: 1,
    advantages: [
      {
        _id: "adv-9",
        title: "Автоматизация рассылок",
        description:
          "Автоматизация рассылок для эффективного взаимодействия с клиентами.",
      },
      {
        _id: "adv-10",
        title: "Персонализация контента",
        description:
          "Персонализация контента для повышения открываемости писем.",
      },
    ],
    createAt: "2023-03-01T00:00:00.000Z",
    updateAt: "2023-03-05T00:00:00.000Z",
    hh: {
      _id: "hh-3",
      count: 80,
      juniorSalary: 50000,
      middleSalary: 75000,
      seniorSalary: 100000,
      updateAt: "2023-02-25T00:00:00.000Z",
    },
  },
  {
    tags: ["Content", "SEO", "Strategy"],
    _id: "service-6",
    secondCategory: "Маркетинг",
    alias: "content-marketing",
    title: "Контент-маркетинг",
    seoText:
      "Разработка и реализация контент-стратегий для привлечения и удержания аудитории.",
    tagsTitle: "Сервисы контент-маркетинга",
    metaTitle: "Контент-маркетинг - Привлекайте больше клиентов",
    metaDescription:
      "Создание привлекательного и полезного контента для вашего бизнеса.",
    firstCategory: 1,
    advantages: [
      {
        _id: "adv-11",
        title: "SEO-оптимизация",
        description: "Оптимизация контента для поисковых систем.",
      },
      {
        _id: "adv-12",
        title: "Создание контента",
        description:
          "Создание различных типов контента: статьи, видео, инфографика.",
      },
    ],
    createAt: "2023-03-01T00:00:00.000Z",
    updateAt: "2023-03-05T00:00:00.000Z",
    hh: {
      _id: "hh-3",
      count: 80,
      juniorSalary: 50000,
      middleSalary: 75000,
      seniorSalary: 100000,
      updateAt: "2023-02-25T00:00:00.000Z",
    },
  },
  {
    tags: ["Logo", "Branding", "Design"],
    _id: "service-7",
    secondCategory: "Дизайн",
    alias: "logo-design",
    title: "Разработка логотипа",
    seoText: "Создание уникальных логотипов, отражающих суть вашего бренда.",
    tagsTitle: "Сервисы разработки логотипов",
    metaTitle: "Разработка логотипа - Создайте свой уникальный стиль",
    metaDescription:
      "Профессиональная разработка логотипов для вашего бизнеса.",
    firstCategory: 2,
    advantages: [
      {
        _id: "adv-13",
        title: "Уникальный дизайн",
        description: "Создание уникального дизайна, отражающего ваш бренд.",
      },
      {
        _id: "adv-14",
        title: "Концепция бренда",
        description: "Разработка концепции бренда на основе ваших ценностей.",
      },
    ],
    createAt: "2023-03-10T00:00:00.000Z",
    updateAt: "2023-03-12T00:00:00.000Z",
    hh: {
      _id: "hh-4",
      count: 60,
      juniorSalary: 55000,
      middleSalary: 80000,
      seniorSalary: 110000,
      updateAt: "2023-03-01T00:00:00.000Z",
    },
  },
  {
    tags: ["UI", "UX", "Audit"],
    _id: "service-8",
    secondCategory: "Дизайн",
    alias: "uiux-audit",
    title: "UI/UX аудит веб-сайта",
    seoText:
      "Проведение UI/UX аудита для улучшения пользовательского опыта на вашем веб-сайте.",
    tagsTitle: "Сервисы UI/UX аудита",
    metaTitle: "UI/UX аудит веб-сайта - Улучшите пользовательский опыт",
    metaDescription: "Профессиональный UI/UX аудит для вашего веб-сайта.",
    firstCategory: 2,
    advantages: [
      {
        _id: "adv-15",
        title: "Анализ юзабилити",
        description: "Анализ юзабилити и удобства использования сайта.",
      },
      {
        _id: "adv-16",
        title: "Рекомендации по улучшению",
        description: "Предоставление рекомендаций по улучшению UI/UX.",
      },
    ],
    createAt: "2023-03-15T00:00:00.000Z",
    updateAt: "2023-03-18T00:00:00.000Z",
    hh: {
      _id: "hh-5",
      count: 40,
      juniorSalary: 55000,
      middleSalary: 80000,
      seniorSalary: 110000,
      updateAt: "2023-03-01T00:00:00.000Z",
    },
  },
  {
    tags: ["Graphics", "Visuals", "Design"],
    _id: "service-9",
    secondCategory: "Дизайн",
    alias: "graphic-design",
    title: "Графический дизайн",
    seoText:
      "Создание визуальных материалов для вашего бренда, включая баннеры, брошюры и др.",
    tagsTitle: "Сервисы графического дизайна",
    metaTitle: "Графический дизайн - Создайте привлекательный визуал",
    metaDescription: "Разработка графического дизайна для вашего бизнеса.",
    firstCategory: 2,
    advantages: [
      {
        _id: "adv-17",
        title: "Индивидуальный подход",
        description: "Индивидуальный подход к каждому клиенту и проекту.",
      },
      {
        _id: "adv-18",
        title: "Широкий спектр услуг",
        description: "Широкий спектр услуг в области графического дизайна.",
      },
    ],
    createAt: "2023-03-15T00:00:00.000Z",
    updateAt: "2023-03-18T00:00:00.000Z",
    hh: {
      _id: "hh-5",
      count: 40,
      juniorSalary: 55000,
      middleSalary: 80000,
      seniorSalary: 110000,
      updateAt: "2023-03-01T00:00:00.000Z",
    },
  },
  {
    tags: ["SEO", "Copywriting", "Content"],
    _id: "service-10",
    secondCategory: "Тексты",
    alias: "seo-copywriting",
    title: "SEO-Копирайтинг",
    seoText:
      "Создание SEO-оптимизированных текстов для привлечения трафика на ваш сайт.",
    tagsTitle: "Сервисы SEO-копирайтинга",
    metaTitle: "SEO-Копирайтинг - Привлекайте больше трафика",
    metaDescription: "Профессиональный SEO-копирайтинг для вашего бизнеса.",
    firstCategory: 3,
    advantages: [
      {
        _id: "adv-19",
        title: "Ключевые слова",
        description: "Оптимизация текстов под ключевые слова.",
      },
      {
        _id: "adv-20",
        title: "Уникальный контент",
        description: "Создание уникального и интересного контента.",
      },
    ],
    createAt: "2023-04-01T00:00:00.000Z",
    updateAt: "2023-05-01T00:00:00.000Z",
    hh: {
      _id: "hh-10",
      count: 90,
      juniorSalary: 65000,
      middleSalary: 95000,
      seniorSalary: 130000,
      updateAt: "2023-04-15T00:00:00.000Z",
    },
  },
  {
    tags: ["Translation", "Languages", "Text"],
    _id: "service-11",
    secondCategory: "Тексты",
    alias: "translation",
    title: "Перевод текста",
    seoText: "Профессиональный перевод текстов с различных языков.",
    tagsTitle: "Сервисы перевода текстов",
    metaTitle: "Перевод текста - Качественный перевод на разные языки",
    metaDescription: "Профессиональный перевод текстов для вашего бизнеса.",
    firstCategory: 3,
    advantages: [
      {
        _id: "adv-21",
        title: "Разные языки",
        description: "Перевод с и на различные языки.",
      },
      {
        _id: "adv-22",
        title: "Точность перевода",
        description: "Обеспечение точности и качества перевода.",
      },
    ],
    createAt: "2023-04-05T00:00:00.000Z",
    updateAt: "2023-05-05T00:00:00.000Z",
    hh: {
      _id: "hh-11",
      count: 70,
      juniorSalary: 55000,
      middleSalary: 80000,
      seniorSalary: 110000,
      updateAt: "2023-04-20T00:00:00.000Z",
    },
  },
  {
    tags: ["Business Plan", "Consulting", "Strategy"],
    _id: "service-12",
    secondCategory: "Консалтинг",
    alias: "business-plan",
    title: "Составление бизнес-плана",
    seoText: "Разработка бизнес-планов для стартапов и развития бизнеса.",
    tagsTitle: "Сервисы составления бизнес-планов",
    metaTitle: "Составление бизнес-плана - Начните свой бизнес правильно",
    metaDescription:
      "Профессиональное составление бизнес-планов для вашего бизнеса.",
    firstCategory: 4,
    advantages: [
      {
        _id: "adv-23",
        title: "Анализ рынка",
        description: "Анализ рынка и конкурентов.",
      },
      {
        _id: "adv-24",
        title: "Финансовая модель",
        description: "Разработка финансовой модели бизнеса.",
      },
    ],
    createAt: "2023-04-10T00:00:00.000Z",
    updateAt: "2023-05-10T00:00:00.000Z",
    hh: {
      _id: "hh-12",
      count: 110,
      juniorSalary: 70000,
      middleSalary: 100000,
      seniorSalary: 140000,
      updateAt: "2023-04-25T00:00:00.000Z",
    },
  },
  {
    tags: ["Finance", "Consulting", "Advice"],
    _id: "service-13",
    secondCategory: "Консалтинг",
    alias: "financial-consulting",
    title: "Финансовый консалтинг",
    seoText:
      "Предоставление консультаций по финансовым вопросам и оптимизации бизнес-процессов.",
    tagsTitle: "Сервисы финансового консалтинга",
    metaTitle: "Финансовый консалтинг - Оптимизируйте свой бизнес",
    metaDescription: "Профессиональные консультации по финансовым вопросам.",
    firstCategory: 4,
    advantages: [
      {
        _id: "adv-25",
        title: "Оптимизация затрат",
        description: "Оптимизация затрат и увеличение прибыли.",
      },
      {
        _id: "adv-26",
        title: "Анализ рисков",
        description:
          "Анализ финансовых рисков и разработка стратегии управления.",
      },
    ],
    createAt: "2023-04-15T00:00:00.000Z",
    updateAt: "2023-05-15T00:00:00.000Z",
    hh: {
      _id: "hh-13",
      count: 85,
      juniorSalary: 60000,
      middleSalary: 85000,
      seniorSalary: 120000,
      updateAt: "2023-04-30T00:00:00.000Z",
    },
  },
  {
    tags: ["Market", "Research", "Analysis"],
    _id: "service-14",
    secondCategory: "Аналитика",
    alias: "market-research",
    title: "Маркетинговое исследование",
    seoText:
      "Проведение маркетинговых исследований для анализа рынка и конкурентов.",
    tagsTitle: "Сервисы маркетинговых исследований",
    metaTitle: "Маркетинговое исследование - Узнайте больше о своем рынке",
    metaDescription:
      "Профессиональные маркетинговые исследования для вашего бизнеса.",
    firstCategory: 5,
    advantages: [
      {
        _id: "adv-27",
        title: "Анализ трендов",
        description: "Анализ текущих рыночных трендов.",
      },
      {
        _id: "adv-28",
        title: "Конкурентный анализ",
        description: "Анализ конкурентов и определение стратегий.",
      },
    ],
    createAt: "2023-05-01T00:00:00.000Z",
    updateAt: "2023-06-01T00:00:00.000Z",
    hh: {
      _id: "hh-16",
      count: 55,
      juniorSalary: 55000,
      middleSalary: 80000,
      seniorSalary: 110000,
      updateAt: "2023-05-15T00:00:00.000Z",
    },
  },
  {
    tags: ["Web", "Analytics", "Data"],
    _id: "service-15",
    secondCategory: "Аналитика",
    alias: "web-analytics",
    title: "Веб-аналитика",
    seoText:
      "Анализ данных веб-сайта для оптимизации и повышения эффективности.",
    tagsTitle: "Сервисы веб-аналитики",
    metaTitle: "Веб-аналитика - Оптимизируйте свой веб-сайт",
    metaDescription: "Профессиональный анализ данных вашего веб-сайта.",
    firstCategory: 5,
    advantages: [
      {
        _id: "adv-29",
        title: "Анализ трафика",
        description: "Анализ трафика и поведения пользователей.",
      },
      {
        _id: "adv-30",
        title: "Отчетность",
        description: "Предоставление детальных отчетов и рекомендаций.",
      },
    ],
    createAt: "2023-05-05T00:00:00.000Z",
    updateAt: "2023-06-05T00:00:00.000Z",
    hh: {
      _id: "hh-17",
      count: 45,
      juniorSalary: 60000,
      middleSalary: 85000,
      seniorSalary: 115000,
      updateAt: "2023-05-20T00:00:00.000Z",
    },
  },
];
