[
  {
    _id: "service-1",
    categories: ["Разработка", "Веб-сайты"],
    tags: ["Frontend", "React"],
    title: "Разработка веб-сайта на React",
    link: "https://example.com/react-website",
    price: 49999,
    credit: 0,
    oldPrice: 59999,
    description:
      "Создание современного и адаптивного веб-сайта с использованием React.",
    characteristic: [
      { value: "2 недели", name: "Срок выполнения" },
      { value: "Поддержка 3 месяца", name: "Гарантия" },
      { value: "Включено", name: "SEO оптимизация" },
    ],
    createAt: "2023-01-01T00:00:00.000Z",
    updateAt: "2023-03-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/react-website.jpg",
    initialRating: 4.7,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Быстрая загрузка, адаптивный дизайн, SEO-оптимизация.",
  },
  {
    _id: "service-2",
    categories: ["Маркетинг", "SMM"],
    tags: ["Instagram", "Продвижение"],
    title: "Продвижение в Instagram",
    link: "https://example.com/instagram-promotion",
    price: 19999,
    credit: 0,
    oldPrice: 24999,
    description: "Комплексное продвижение вашего бизнеса в Instagram.",
    characteristic: [
      { value: "30 дней", name: "Срок выполнения" },
      { value: "Таргетированная реклама", name: "Метод продвижения" },
      { value: "Ежедневная отчетность", name: "Отчетность" },
    ],
    createAt: "2023-02-01T00:00:00.000Z",
    updateAt: "2023-03-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/instagram-promotion.jpg",
    initialRating: 4.5,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages:
      "Привлечение целевой аудитории, увеличение узнаваемости бренда.",
  },
  {
    _id: "service-3",
    categories: ["Дизайн", "Логотипы"],
    tags: ["Разработка логотипа", "Брендинг"],
    title: "Разработка логотипа",
    link: "https://example.com/logo-design",
    price: 9999,
    credit: 0,
    oldPrice: 12999,
    description: "Создание уникального логотипа для вашего бизнеса.",
    characteristic: [
      { value: "5 вариантов", name: "Количество концепций" },
      { value: "Неограниченные правки", name: "Правки" },
      { value: "Исходники в векторе", name: "Формат файлов" },
    ],
    createAt: "2023-03-01T00:00:00.000Z",
    updateAt: "2023-04-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/logo-design.jpg",
    initialRating: 4.8,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages:
      "Уникальный дизайн, отражение ценностей компании, запоминающийся образ.",
  },
  {
    _id: "service-4",
    categories: ["Тексты", "Копирайтинг"],
    tags: ["Статьи", "SEO"],
    title: "SEO-Копирайтинг",
    link: "https://example.com/seo-copywriting",
    price: 2999,
    credit: 0,
    oldPrice: 3499,
    description: "Написание SEO-оптимизированных статей для вашего сайта.",
    characteristic: [
      { value: "5 статей", name: "Количество статей" },
      { value: "5000 символов", name: "Объем статьи" },
      { value: "Ключевые слова включены", name: "Оптимизация" },
    ],
    createAt: "2023-04-01T00:00:00.000Z",
    updateAt: "2023-05-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/seo-copywriting.jpg",
    initialRating: 4.6,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages:
      "Привлечение органического трафика, улучшение позиций в поисковых системах.",
  },
  {
    _id: "service-5",
    categories: ["Консалтинг", "Бизнес"],
    tags: ["Бизнес-план", "Стартап"],
    title: "Составление бизнес-плана",
    link: "https://example.com/business-plan",
    price: 24999,
    credit: 0,
    oldPrice: 29999,
    description:
      "Разработка профессионального бизнес-плана для вашего стартапа.",
    characteristic: [
      { value: "Детальный анализ рынка", name: "Содержание" },
      { value: "Финансовая модель", name: "Содержание" },
      { value: "Презентация", name: "Формат" },
    ],
    createAt: "2023-05-01T00:00:00.000Z",
    updateAt: "2023-06-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/business-plan.jpg",
    initialRating: 4.9,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages:
      "Четкая стратегия развития, привлечение инвестиций, минимизация рисков.",
  },
  {
    _id: "service-6",
    categories: ["Аналитика", "Исследования"],
    tags: ["Маркетинговое исследование", "Рынок"],
    title: "Маркетинговое исследование",
    link: "https://example.com/market-research",
    price: 14999,
    credit: 0,
    oldPrice: 17999,
    description: "Проведение маркетингового исследования рынка.",
    characteristic: [
      { value: "Анализ конкурентов", name: "Содержание" },
      { value: "Анализ целевой аудитории", name: "Содержание" },
      { value: "Рекомендации", name: "Формат" },
    ],
    createAt: "2023-06-01T00:00:00.000Z",
    updateAt: "2023-07-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/market-research.jpg",
    initialRating: 4.8,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages:
      "Понимание рынка, улучшение маркетинговой стратегии, увеличение прибыли.",
  },
  {
    _id: "service-7",
    categories: ["Разработка", "Мобильные приложения"],
    tags: ["iOS", "Android"],
    title: "Разработка мобильного приложения",
    link: "https://example.com/mobile-app-development",
    price: 79999,
    credit: 0,
    oldPrice: 89999,
    description: "Создание нативного мобильного приложения для iOS и Android.",
    characteristic: [
      { value: "6 недель", name: "Срок выполнения" },
      { value: "Публикация в App Store и Google Play", name: "Услуга" },
      { value: "Бесплатные обновления 3 месяца", name: "Поддержка" },
    ],
    createAt: "2023-07-01T00:00:00.000Z",
    updateAt: "2023-08-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/mobile-app-development.jpg",
    initialRating: 4.7,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Расширение аудитории, повышение лояльности клиентов.",
  },
  {
    _id: "service-8",
    categories: ["Маркетинг", "Email-маркетинг"],
    tags: ["Рассылки", "Автоматизация"],
    title: "Email-маркетинг",
    link: "https://example.com/email-marketing",
    price: 9999,
    credit: 0,
    oldPrice: 11999,
    description: "Настройка и ведение email-маркетинговой кампании.",
    characteristic: [
      { value: "Анализ базы данных", name: "Этап 1" },
      { value: "Создание шаблонов писем", name: "Этап 2" },
      { value: "Автоматизация рассылок", name: "Этап 3" },
    ],
    createAt: "2023-08-01T00:00:00.000Z",
    updateAt: "2023-09-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/email-marketing.jpg",
    initialRating: 4.6,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Повышение конверсии, укрепление отношений с клиентами.",
  },
  {
    _id: "service-9",
    categories: ["Дизайн", "Веб-дизайн"],
    tags: ["UI/UX", "Аудит"],
    title: "UI/UX аудит веб-сайта",
    link: "https://example.com/uiux-audit",
    price: 4999,
    credit: 0,
    oldPrice: 5999,
    description:
      "Анализ текущего UI/UX вашего веб-сайта с рекомендациями по улучшению.",
    characteristic: [
      { value: "Экспертная оценка", name: "Метод анализа" },
      { value: "Отчет с рекомендациями", name: "Результат" },
      { value: "Поддержка после аудита", name: "Гарантия" },
    ],
    createAt: "2023-09-01T00:00:00.000Z",
    updateAt: "2023-10-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/uiux-audit.jpg",
    initialRating: 4.8,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Улучшение пользовательского опыта, повышение конверсии.",
  },
  {
    _id: "service-10",
    categories: ["Тексты", "Переводы"],
    tags: ["Английский", "Русский"],
    title: "Перевод текста",
    link: "https://example.com/translation",
    price: 1499,
    credit: 0,
    oldPrice: 1799,
    description:
      "Профессиональный перевод текста с английского на русский и наоборот.",
    characteristic: [
      { value: "Носитель языка", name: "Переводчик" },
      { value: "Проверка редактором", name: "Контроль качества" },
      { value: "Соблюдение сроков", name: "Гарантия" },
    ],
    createAt: "2023-10-01T00:00:00.000Z",
    updateAt: "2023-11-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/translation.jpg",
    initialRating: 4.9,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Высокое качество перевода, соблюдение терминологии.",
  },
  {
    _id: "service-11",
    categories: ["Консалтинг", "Финансы"],
    tags: ["Инвестиции", "Анализ"],
    title: "Финансовый консалтинг",
    link: "https://example.com/financial-consulting",
    price: 34999,
    credit: 0,
    oldPrice: 39999,
    description:
      "Предоставление экспертных консультаций по финансовому планированию и инвестициям.",
    characteristic: [
      { value: "Оценка рисков", name: "Первый этап" },
      { value: "Разработка стратегии", name: "Второй этап" },
      { value: "Сопровождение", name: "Третий этап" },
    ],
    createAt: "2023-11-01T00:00:00.000Z",
    updateAt: "2023-12-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/financial-consulting.jpg",
    initialRating: 4.7,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Увеличение доходности, снижение рисков.",
  },
  {
    _id: "service-12",
    categories: ["Аналитика", "Веб-аналитика"],
    tags: ["Google Analytics", "Отчетность"],
    title: "Веб-аналитика",
    link: "https://example.com/web-analytics",
    price: 7999,
    credit: 0,
    oldPrice: 8999,
    description:
      "Настройка и анализ веб-аналитики для вашего сайта с предоставлением отчетов.",
    characteristic: [
      { value: "Настройка Google Analytics", name: "Первый этап" },
      { value: "Анализ данных", name: "Второй этап" },
      { value: "Подготовка отчетов", name: "Третий этап" },
    ],
    createAt: "2023-12-01T00:00:00.000Z",
    updateAt: "2024-01-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/web-analytics.jpg",
    initialRating: 4.8,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Понимание поведения пользователей, оптимизация сайта.",
  },
  {
    _id: "service-13",
    categories: ["Разработка", "Чат-боты"],
    tags: ["Telegram", "WhatsApp"],
    title: "Разработка чат-бота",
    link: "https://example.com/chatbot-development",
    price: 29999,
    credit: 0,
    oldPrice: 34999,
    description:
      "Создание чат-бота для Telegram и WhatsApp для автоматизации общения с клиентами.",
    characteristic: [
      { value: "Сбор требований", name: "Первый этап" },
      { value: "Разработка логики", name: "Второй этап" },
      { value: "Тестирование и запуск", name: "Третий этап" },
    ],
    createAt: "2024-01-01T00:00:00.000Z",
    updateAt: "2024-02-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/chatbot-development.jpg",
    initialRating: 4.9,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Автоматизация поддержки, увеличение продаж.",
  },
  {
    _id: "service-14",
    categories: ["Маркетинг", "Контент-маркетинг"],
    tags: ["Блог", "Статьи"],
    title: "Контент-маркетинг",
    link: "https://example.com/content-marketing",
    price: 12999,
    credit: 0,
    oldPrice: 14999,
    description:
      "Разработка и реализация стратегии контент-маркетинга для привлечения аудитории.",
    characteristic: [
      { value: "Анализ целевой аудитории", name: "Первый этап" },
      { value: "Разработка контент-плана", name: "Второй этап" },
      { value: "Создание и публикация контента", name: "Третий этап" },
    ],
    createAt: "2024-02-01T00:00:00.000Z",
    updateAt: "2024-03-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/content-marketing.jpg",
    initialRating: 4.8,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Привлечение лидов, повышение узнаваемости бренда.",
  },
  {
    _id: "service-15",
    categories: ["Дизайн", "Графический дизайн"],
    tags: ["Баннеры", "Реклама"],
    title: "Графический дизайн",
    link: "https://example.com/graphic-design",
    price: 5999,
    credit: 0,
    oldPrice: 6999,
    description:
      "Создание графического контента для вашего бизнеса (баннеры, листовки, и т.д.).",
    characteristic: [
      { value: "Разработка концепции", name: "Первый этап" },
      { value: "Создание макетов", name: "Второй этап" },
      { value: "Финальные правки", name: "Третий этап" },
    ],
    createAt: "2024-03-01T00:00:00.000Z",
    updateAt: "2024-04-01T00:00:00.000Z",
    _v: 1,
    image: "https://example.com/images/graphic-design.jpg",
    initialRating: 4.9,
    reviews: [],
    reviewsCount: 0,
    reviewsAvg: 0,
    advantages: "Привлечение внимания, повышение конверсии.",
  },
];
